services:
  quizon-app:
    image: snikimonk/quizon:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8000:8000'
    environment:
      - PG_DSN=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable
      - DOMAIN=${DOMAIN}

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

