openapi: "3.0.0"
info:
  version: 1.0.0
  title: quizon server api
paths:
  /games/{id}/registrations:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRegistrationsResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /games:
    get:
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: per_page
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListGamesResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /registration:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRegistrationRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRegistrationResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /game:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGameResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dummy'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dummy'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Dummy:
      type: object
      properties:
    Error:
      type: object
      required: [error]
      properties:
        error:
          type: string
    RegistrationStatus:
      type: string
      enum: ["ok", "reserve", "closed"]
    ListRegistrationsItem:
      type: object
      required: [number, telegram, team_name, captain_name, phone, players_amount, registered_at]
      properties:
        number:
          type: integer
          format: int64
        telegram:
          type: string
        team_id:
          type: string
        team_name:
          type: string
        captain_name:
          type: string
        phone:
          type: string
        group_name:
          type: string
        players_amount:
          type: integer
          format: int64
        registered_at:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28Z'
    ListRegistrationsResponse:
      type: array
      items:
        type: array
        $ref: '#/components/schemas/ListRegistrationsItem'
    ListGamesItem:
      type: object
      required: [id, start_time, location, name, main_amount, reserve_amount, registration_open_time, registration_status]
      properties:
        id:
          type: integer
          format: int64
        start_time:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28Z'
        location:
          type: string
        name:
          type: string
        main_amount:
          type: integer
          format: int64
        reserve_amount:
          type: integer
          format: int64
        registration_open_time:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28Z'
        registration_status:
          $ref: '#/components/schemas/RegistrationStatus'
    ListGamesResponse:
      type: array
      items:
        type: array
        $ref: '#/components/schemas/ListGamesItem'
    CreateRegistrationRequest:
      type: object
      required: [game_id, telegram, team_name, captain_name, phone, players_amount]
      properties:
        game_id:
          type: integer
          format: int64
        telegram:
          type: string
        team_id:
          type: string
        team_name:
          type: string
        captain_name:
          type: string
        phone:
          type: string
        group_name:
          type: string
        players_amount:
          type: integer
          format: int64
    CreateRegistrationResponse:
      type: object
      required: [status]
      properties:
        status:
          $ref: '#/components/schemas/RegistrationStatus'
    CreateGameRequest:
      type: object
      required: [start_time, location, name, main_amount, reserve_amount, registration_open_time]
      properties:
        start_time:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28Z'
        location:
          type: string
        name:
          type: string
        main_amount:
          type: integer
          format: int64
        reserve_amount:
          type: integer
          format: int64
        registration_open_time:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28Z'
    CreateGameResponse:
      type: object
      required: [id]
      properties:
        id:
          type: integer
          format: int64
    LoginRequest:
      type: object
      required: [login, password]
      properties:
        login:
          type: string
        password:
          type: string
