//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Cookies struct {
	UserID    int32 `db:"user_id"`
	Value     uuid.UUID `db:"value"`
	ExpiresAt time.Time `db:"expires_at"`
}
