//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Games struct {
	ID              int32 `sql:"primary_key"`
	Name            string
	Description     string
	Date            time.Time
	TeamsAmount     int32
	PricePerPerson  int32
	Location        string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       int32
	RegisteredTeams int32
}
