//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Registrations struct {
	ID                 int32 `sql:"primary_key"`
	GameID             int32
	TeamName           string
	CaptainName        string
	Phone              string
	Telega             string
	Amount             int32
	RegistrationNumber int32
	CreatedAt          time.Time
}
