name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_HOST_AUTH_METHOD: trust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: install migration tool
      run: go install github.com/pressly/goose/v3/cmd/goose@latest

    - name: run migrations
      run: make migrate-up

    - name: run tests
      run: make test-cov
